# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-24 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_completed',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
