# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_auto_20170525_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='notes',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_notes',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
