# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0003_auto_20170526_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
