# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('item_name', models.CharField(max_length=40)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_purchased', models.DateTimeField(null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=40)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('store_notes', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='g2.Store'),
        ),
    ]
